# HTML

# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'set VUE_APP_TITLE=$(Build.VUE_APP_TITLE)'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'set VUE_APP_URL=$(Build.VUE_APP_URL)'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build'
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://$(Build.FTP_SERVER)'
    username: '$(Build.FTP_USERNAME)'
    password: '$(Build.FTP_PASSWORD)'
    rootDirectory: './dist'
    filePatterns: '**'
    remoteDirectory: '/staging.devitup.co.uk/public/'
    clean: false
    cleanContents: true
    preservePaths: false
    trustSSL: false